version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sample-202111"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q5j9wbdgtwue"
s3_prefix = "aws-sample-202111"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Env=\"dev\""
